baseURL = "https://zak-ke.github.io/zak-ke/"
publishDir = "docs"
languageCode = "zh-tw"
title = "札刻 | Zak刻 (Zak-Ke)"
theme = "PaperMod"

# 列表每頁數、摘要長度
pagination = { pageSize = 10 }
summaryLength = 80

relativeURLs = true
canonifyURLs = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

# 讓首頁輸出 JSON 供搜尋使用
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  author = "Zak"
  defaultTheme = "auto" # auto = 跟隨系統, dark = 深色, light = 淺色
  disableThemeToggle = false
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  comments = false               # 之後要留言系統再改 true

  # 首頁上方簡介（簡潔好看）
  [params.homeInfoParams]
    Title = "札刻 Zak-Ke"
    Content = "創作與翻譯的刻痕：小說章節、公告與常見問題。"

 # 文章封面顯示規則
  [params.cover]
    linkFullImages = true
    hidden = false
    hiddenInList = false
    hiddenInSingle = false

  [params.assets]
    disableFingerprinting = true   

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首頁"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "announcement"
    name = "會員公告"
    url = "/announcement/"
    weight = 3

  [[menu.main]]
    identifier = "novels"
    name = "小說列表"
    url = "/novels/"
    weight = 4

  [[menu.main]]
    identifier = "faq"
    name = "網站問題"
    url = "/faq/"
    weight = 5

  [[menu.main]]
    identifier = "search"
    name = "搜尋"
    url = "/search/"
    weight = 6

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/zak-ke"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:dng.workplace@gmail.com"

